name: artifact

env: 
  ARTIFACT_NAME_VARIABLE: 'Readme.md'

on: push

jobs:
  checkout-job:
    runs-on: macos-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with: 
          name: ${{ env.ARTIFACT_NAME_VARIABLE }}
          path: .
